POST http://localhost:3001/api/user HTTP/1.1
content-type: application/json 

{
  "email": "saffiegajaga@gmail.com",
  "password": "not visible",
  "firstname": "ssaffie",
  "minit": "",
  "lastname": "sillah"}

###
POST http://localhost:3001/api/knowledge HTTP/1.1
content-type: application/json 

{
"week":"seven",
"title":"knowledge",
"image":"screening",
"user":"63949b7f0158222e31ec38ec"
}

