DELETE http://localhost:3001/api/user/6396fef55d736b2ed43d8e38
Content-Type: application/json





### knowledge
DELETE http://localhost:3001/api/knowledge/63773a79fcbfd67de6919422
content-type: application/json
{
  "userId": "636b76ea9daaabbcecf21442"
}
